version: '3'

tasks:
  setup:
    desc: "Package helm-core and inject it into helm-templates/charts/ for local development"
    cmds:
      - rm -rf charts/ ./**/*.lock ./**/*.tgz

  lint:
    desc: Lint the chart (validates structure and JSON schema)
    cmds:
      - helm lint . -f tests/_shared/common.yaml -f tests/_shared/prod.yaml

  template:
    desc: Render the chart
    cmds:
      - helm template test . -f tests/_shared/common.yaml -f tests/_shared/prod.yaml

  test:
    desc: Run helm-templates unit tests against local helm-core
    cmds:
      - helm unittest . -f 'tests/**/*_test.yaml'
