{{- if .Values.cronJob.enabled }}
{{- $config := include "core.general.config" . | fromYaml }}
{{- $context := merge (dict "$" $) $config }}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "core.cronjob.name" $context }}
  labels:
    {{- include "core.general.labels" $context | nindent 4 }}
    {{- with $config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with ($config.annotations).cronJob }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ $config.cronJob.schedule | quote }}
  suspend: {{ include "core.cronjob.suspend" $context }}
  concurrencyPolicy: {{ include "core.cronjob.concurrencyPolicy" $context }}
  successfulJobsHistoryLimit: {{ include "core.cronjob.successfulJobsHistoryLimit" $context }}
  failedJobsHistoryLimit: {{ include "core.cronjob.failedJobsHistoryLimit" $context }}
  jobTemplate:
    spec:
      completions: 1
      template:
        spec:
          serviceAccountName: {{ include "core.pod.serviceaccount" $context }}
          {{- with (include "core.pod.imagePullSecrets" $context) }}
          imagePullSecrets: {{ . | indent 10 }}
          {{- end }}
          {{- with (include "core.pod.volumes" $context) }}
          volumes: {{ . | indent 10 }}
          {{- end }}
          {{- with (include "core.pod.initContainers" $context) }}
          initContainers: {{ . | indent 10 }}
          {{- end }}
          {{- with (include "core.pod.priorityClassName" $context) }}
          priorityClassName: {{ . }}
          {{- end }}
          {{- with (include "core.pod.nodeSelector" $context) }}
          nodeSelector: {{ . | nindent 10 }}
          {{- end }}
          {{- with (include "core.pod.affinity" $context) }}
          affinity: {{ . | nindent 10 }}
          {{- end }}
          {{- with (include "core.pod.tolerations" $context) }}
          tolerations: {{ . | nindent 10 }}
          {{- end }}
          {{- with (include "core.pod.hostAliases" $context) }}
          hostAliases: {{ . | nindent 10 }}
          {{- end }}
          {{- with (include "core.pod.securityContext" $context) }}
          securityContext: {{ . | nindent 10 }}
          {{- end }}
          containers: {{ include "core.container.render" $context | indent 12 }}
          restartPolicy: OnFailure
{{- end }}
