{{- if .Values.cronJob.enabled }}
{{- $config := include "core.general.config" . | fromYaml }}
{{- $context := merge (dict "$" $) $config }}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "core.cronjob.name" $context }}
  labels:
    {{- include "core.general.labels" $context | nindent 4 }}
    {{- with $config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with ($config.annotations).cronJob }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ $config.cronJob.schedule | quote }}
  concurrencyPolicy: {{ $config.cronJob.concurrencyPolicy | default "Forbid" }}
  successfulJobsHistoryLimit: {{ int $config.cronJob.successfulJobsHistory | default 3 }}
  failedJobsHistoryLimit: {{ int $config.cronJob.failedJobsHistory | default 1 }}
  jobTemplate:
    spec:
      completions: 1
      template:
        spec:
          serviceAccountName: {{ include "core.pod.serviceaccount" $context }}
          {{- with (include "core.pod.imagePullSecrets" $context) }}
          imagePullSecrets: {{ . | indent 10 }}
          {{- end }}
          {{- with (include "core.pod.volumes" $context) }}
          volumes: {{ . | indent 10 }}
          {{- end }}
          {{- with (include "core.pod.initContainers" $context) }}
          initContainers: {{ . | indent 10 }}
          {{- end }}
          containers: {{ include "core.container.render" $context | indent 12 }}
          restartPolicy: OnFailure
{{- end }}
