{{- if .Values.deployment.enabled }}
{{- $config := include "core.general.config" . | fromYaml }}
{{- $context := merge (dict "$" $) $config }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "core.deployment.name" $context }}
  labels:
    {{- include "core.deployment.labels" $context | nindent 4 }}
    {{- with $config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with ($config.annotations).deployment }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ include "core.deployment.replicas" $context }}
  selector:
    matchLabels: {{ include "core.common.labels" $context | nindent 6 }}
  revisionHistoryLimit: {{ ternary 1 (int $config.revisionHistoryLimit) (kindIs "invalid" $config.revisionHistoryLimit) }}
  strategy: {{ include "core.common.strategy.rollingUpdate" $context | nindent 4 }}
  template:
    metadata:
      labels: {{ include "core.common.labels" $context | nindent 8 }}
      {{- with (include "core.pod.annotations" $context) }}
      annotations: {{ . | indent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ $config.serviceAccount | default "default" }}
      {{- with (include "core.pod.imagePullSecrets" $context) }}
      imagePullSecrets: {{ . | indent 6 }}
      {{- end }}
      {{- with (include "core.pod.volumes" $context) }}
      volumes: {{ . | indent 6 }}
      {{- end }}
      {{- with (include "core.pod.initContainers" $context) }}
      initContainers: {{ . | indent 6 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ ternary 30 (int $config.terminationGracePeriodSeconds) (kindIs "invalid" $config.terminationGracePeriodSeconds) }}
      topologySpreadConstraints: {{ include "core.pod.topologySpreadConstraints" $context | nindent 6 }}
      containers: 
        {{- include "core.container.render" $context | indent 8 }}
        {{- with (include "core.container.sidecars" $context) }}
        {{- . | indent 8 }}
        {{- end }}
{{- end }}
