{{- if eq (.Values.workload).type "Deployment" }}
{{- $config := include "core.general.config" . | fromYaml }}
{{- $context := merge (dict "$" $) $config }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "core.deployment.name" $context }}
  labels:
    {{- include "core.workload.labels" $context | nindent 4 }}
    {{- with $config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with ($config.annotations).deployment }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ include "core.workload.replicas" $context }}
  selector:
    matchLabels: {{ include "core.general.selectorLabels" $context | nindent 6 }}
  revisionHistoryLimit: {{ include "core.workload.revisionHistoryLimit" $context }}
  strategy: {{ include "core.workload.strategy" $context | nindent 4 }}
  template:
    metadata:
      labels: {{ include "core.general.selectorLabels" $context | nindent 8 }}
      {{- with (include "core.pod.annotations" $context) }}
      annotations: {{ . | indent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "core.pod.serviceaccount" $context }}
      {{- with (include "core.pod.imagePullSecrets" $context) }}
      imagePullSecrets: {{ . | indent 8 }}
      {{- end }}
      {{- with (include "core.pod.volumes" $context) }}
      volumes: {{ . | indent 8 }}
      {{- end }}
      {{- with (include "core.pod.initContainers" $context) }}
      initContainers: {{ . | indent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ include "core.pod.terminationGracePeriodSeconds" $context }}
      {{- with (include "core.pod.topologySpreadConstraints" $context) }}
      topologySpreadConstraints: {{ . | indent 8 }}
      {{- end }}
      {{- with (include "core.pod.priorityClassName" $context) }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with (include "core.pod.nodeSelector" $context) }}
      nodeSelector: {{ . | nindent 8 }}
      {{- end }}
      {{- with (include "core.pod.affinity" $context) }}
      affinity: {{ . | nindent 8 }}
      {{- end }}
      {{- with (include "core.pod.tolerations" $context) }}
      tolerations: {{ . | nindent 8 }}
      {{- end }}
      {{- with (include "core.pod.securityContext" $context) }}
      securityContext: {{ . | nindent 8 }}
      {{- end }}
      containers:
        {{- include "core.container.render" $context | indent 8 }}
        {{- with (include "core.container.sidecars" $context) }}
        {{- . | indent 8 }}
        {{- end }}
{{- end }}
