{{- if and (eq (.Values.hpa).enabled true) (eq (.Values.workload).enabled true) }}
{{- $config := include "core.general.config" . | fromYaml }}
{{- $context := merge (dict "$" $) $config }}
{{- if and (not $config.activeRegion) $config.hpa }}
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: {{ include "core.hpa.name" $context }}
  {{- with ($config.annotations).hpa }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef: {{ include "core.hpa.workloadRef" $context | nindent 4 }}
  minReplicas: {{ $config.replicas }}
  maxReplicas: {{ $config.hpa.maxReplicas }}
  metrics: {{ include "core.hpa.metrics" $context | nindent 2 }}
{{- end }}
{{- end }}
