{{- if and .Values.hpa.enabled (ne (.Values.workload).type "DaemonSet") }}
{{- $config := include "core.general.config" . | fromYaml }}
{{- $context := merge (dict "$" $) $config }}
{{- if and (not $config.activeRegion) $config.hpa }}
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: {{ include "core.hpa.name" $context }}
  {{- with ($config.annotations).hpa }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ include "core.deployment.name" $context }}
    apiVersion: apps/v1
  minReplicas: {{ $config.replicas }}
  maxReplicas: {{ $config.hpa.maxReplicas }}
  metrics:
  {{- range $resource, $target := ($config.hpa).resources }}
  - type: Resource
    resource:
      name: {{ $resource }}
      target:
        type: Utilization
        averageUtilization: {{ $target.averageUtilization | default 70 }}
  {{- end }}
{{- end }}
{{- end }}
