{{- if (.Values.serviceAccount).create }}
{{- $config := include "core.general.config" . | fromYaml }}
{{- $context := merge (dict "$" $) $config }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "core.serviceaccount.name" $context }}
  labels:
    {{- include "core.general.labels" $context | nindent 4 }}
    {{- with $config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with ($config.annotations).serviceAccount }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with ($config.serviceAccount).imagePullSecrets }}
imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
