name: Publish new Helm Templates version

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v4
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull dependencies
        run: helm dependency update
      
      - name: Package chart
        run: helm package .

      - name: Push to GHCR
        run: helm push templates-*.tgz oci://ghcr.io/${{ github.repository_owner }}/helm-charts
